image: node:latest

stages:
  - build
  - test
  - deploy

variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "develop"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
